import { BlogPost, NavLinkItem, ProductPlan, ProductType } from "./types";


export const PRODUCT_PLANS: ProductPlan[] = [
  // Cloud Server
  {
    id: 'cloud-1',
    name: 'Cloud Basic NVMe',
    price: '150.000đ/tháng',
    cpu: '2 vCPU',
    ram: '4 GB',
    disk: '50 GB NVMe',
    bandwidth: 'Unlimited',
    type: ProductType.CLOUD_SERVER,
    features: ['Backup hàng ngày', 'IPv4 riêng', 'Hỗ trợ 24/7', 'Uptime 99.9%'],
  },
  {
    id: 'cloud-2',
    name: 'Cloud Pro NVMe',
    price: '350.000đ/tháng',
    cpu: '4 vCPU',
    ram: '8 GB',
    disk: '100 GB NVMe',
    bandwidth: 'Unlimited',
    type: ProductType.CLOUD_SERVER,
    features: ['Backup hàng ngày', 'Snapshot miễn phí', 'Ưu tiên hỗ trợ', 'Miễn phí DirectAdmin'],
    popular: true,
  },
  {
    id: 'cloud-3',
    name: 'Cloud Elite NVMe',
    price: '650.000đ/tháng',
    cpu: '8 vCPU',
    ram: '16 GB',
    disk: '200 GB NVMe',
    bandwidth: 'Unlimited',
    type: ProductType.CLOUD_SERVER,
    features: ['Backup Realtime', 'IP Riêng (x2)', 'VIP Support', 'Anti-DDoS Pro'],
  },
  {
    id: 'cloud-4',
    name: 'Cloud Enterprise',
    price: '1.200.000đ/tháng',
    cpu: '16 vCPU',
    ram: '32 GB',
    disk: '400 GB NVMe',
    bandwidth: 'Unlimited',
    type: ProductType.CLOUD_SERVER,
    features: ['Hạ tầng riêng biệt', 'Load Balancing', 'Private Network', 'SLA 99.99%'],
  },
  // VPS
  {
    id: 'vps-1',
    name: 'VPS Giá Rẻ SSD',
    price: '80.000đ/tháng',
    cpu: '1 Core',
    ram: '2 GB',
    disk: '25 GB SSD',
    bandwidth: '100 Mbps',
    type: ProductType.VPS,
    features: ['Kích hoạt tự động', 'Full quyền Root', 'Datacenter Việt Nam'],
  },
  {
    id: 'vps-2',
    name: 'VPS Business',
    price: '220.000đ/tháng',
    cpu: '4 Core',
    ram: '8 GB',
    disk: '80 GB SSD',
    bandwidth: '200 Mbps',
    type: ProductType.VPS,
    features: ['Tối ưu Database', 'Firewall cơ bản', 'Windows/Linux OS', 'IP Sạch'],
    popular: true,
  },
  {
    id: 'vps-3',
    name: 'VPS Gaming',
    price: '450.000đ/tháng',
    cpu: '6 Core High Perf',
    ram: '12 GB',
    disk: '120 GB NVMe',
    bandwidth: '500 Mbps',
    type: ProductType.VPS,
    features: ['CPU xung nhịp cao', 'Anti-DDoS Game', 'Treo Tool 24/7', 'Support cài Game'],
  },
  {
    id: 'vps-4',
    name: 'VPS Storage',
    price: '300.000đ/tháng',
    cpu: '2 Core',
    ram: '4 GB',
    disk: '500 GB HDD',
    bandwidth: '100 Mbps',
    type: ProductType.VPS,
    features: ['Lưu trữ dữ liệu lớn', 'Backup tự động', 'Raid 10 an toàn', 'Truy xuất nhanh'],
  },
  // Proxy
  {
    id: 'proxy-1',
    name: 'IPv4 Private Proxy',
    price: '30.000đ/proxy',
    cpu: 'N/A',
    ram: 'N/A',
    disk: 'N/A',
    bandwidth: 'Unlimited',
    type: ProductType.PROXY,
    features: ['IP tĩnh riêng biệt', 'HTTP/SOCKS5', 'Uptime 99.9%', 'Nuôi Ebay/Amazon'],
  },
  {
    id: 'proxy-2',
    name: '4G Mobile Proxy',
    price: '500.000đ/tháng',
    cpu: 'N/A',
    ram: 'N/A',
    disk: 'N/A',
    bandwidth: 'Unlimited',
    type: ProductType.PROXY,
    features: ['Đổi IP tự động', 'Tốc độ cao 40Mbps', 'Không giới hạn luồng', 'Nhà mạng Viettel/Vina'],
    popular: true,
  },
  {
    id: 'proxy-3',
    name: 'IPv6 Rotating',
    price: '200.000đ/tháng',
    cpu: 'N/A',
    ram: 'N/A',
    disk: 'N/A',
    bandwidth: 'Unlimited',
    type: ProductType.PROXY,
    features: ['Hàng triệu IP', 'Xoay IP mỗi request', 'Phù hợp Crawl Data', 'Giá rẻ tiết kiệm'],
  },
  {
    id: 'proxy-4',
    name: 'Residential Proxy',
    price: '150.000đ/GB',
    cpu: 'N/A',
    ram: 'N/A',
    disk: 'N/A',
    bandwidth: 'Theo dung lượng',
    type: ProductType.PROXY,
    features: ['IP dân cư thật', 'Không bị block', 'Target quốc gia', 'Thanh toán PAYG'],
  },
  // Dedicated
  {
    id: 'dedi-1',
    name: 'Dell PowerEdge R640',
    price: '3.500.000đ/tháng',
    cpu: '2x Gold 6138',
    ram: '128 GB DDR4',
    disk: '2x 960GB NVMe',
    bandwidth: '1 Gbps',
    type: ProductType.DEDICATED,
    features: ['Toàn quyền root', 'Datacenter Tier 3', 'Phần cứng riêng biệt', 'IPMI/KVM Online'],
  },
  {
    id: 'dedi-2',
    name: 'Dell PowerEdge R740',
    price: '5.500.000đ/tháng',
    cpu: '2x Gold 6248R',
    ram: '256 GB DDR4',
    disk: '4x 1.92TB NVMe',
    bandwidth: '10 Gbps',
    type: ProductType.DEDICATED,
    features: ['Hiệu năng cực khủng', 'Chạy ảo hóa tốt', 'Private Network', 'Hỗ trợ 24/7 VIP'],
  },
  {
    id: 'dedi-3',
    name: 'HP ProLiant DL380',
    price: '4.200.000đ/tháng',
    cpu: '2x Gold 6140',
    ram: '192 GB DDR4',
    disk: '2x 480GB SSD',
    bandwidth: '1 Gbps',
    type: ProductType.DEDICATED,
    features: ['Ổn định cao', 'Thích hợp Database', 'iLO Advanced', 'Bảo hành phần cứng'],
  },
  // Anti DDoS
  {
    id: 'ddos-1',
    name: 'L4/L7 Protection',
    price: '500.000đ/tháng',
    cpu: 'AI Filter',
    ram: 'Global Node',
    disk: 'N/A',
    bandwidth: 'Clean Traffic',
    type: ProductType.ANTI_DDOS,
    features: ['Chống TCP Flood', 'UDP Flood', 'Game Anti-DDoS', 'WAF Protection'],
  },
  {
    id: 'ddos-2',
    name: 'Enterprise Guard',
    price: '2.000.000đ/tháng',
    cpu: 'Custom Rules',
    ram: 'Multi-CDN',
    disk: 'N/A',
    bandwidth: 'Unlimited Clean',
    type: ProductType.ANTI_DDOS,
    features: ['Chuyên dụng cho Game', 'Hỗ trợ FiveM/SAMP', 'Báo cáo Realtime', 'Chuyên gia hỗ trợ'],
    popular: true,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Tại sao nên chuyển từ Shared Hosting sang Cloud Server?',
    excerpt: 'Khám phá những lợi ích vượt trội về hiệu năng, bảo mật và độ ổn định khi nâng cấp hệ thống của bạn lên Cloud Server NVMe.',
    date: '20/05/2024',
    author: 'Admin',
    category: 'Kiến thức',
    imageUrl: 'https://images.unsplash.com/photo-1483478550801-ceba96c89ae7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '2',
    title: 'Hướng dẫn cài đặt Proxy Server riêng tư an toàn',
    excerpt: 'Bảo mật danh tính và dữ liệu của bạn trên internet với hướng dẫn thiết lập Proxy IPv4 Private chi tiết trên Linux.',
    date: '18/05/2024',
    author: 'Kỹ thuật',
    category: 'Hướng dẫn',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '3',
    title: 'Anti-DDoS hoạt động như thế nào trong Game Online?',
    excerpt: 'Tìm hiểu cơ chế hoạt động của các cuộc tấn công từ chối dịch vụ vào Game Server và giải pháp phòng chống hiệu quả.',
    date: '15/05/2024',
    author: 'Security Team',
    category: 'Bảo mật',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '4',
    title: 'Top 5 Distro Linux tốt nhất cho Web Server 2024',
    excerpt: 'Đánh giá chi tiết ưu nhược điểm của Ubuntu, CentOS, Debian, AlmaLinux và Rocky Linux cho môi trường Production.',
    date: '10/06/2024',
    author: 'SysAdmin',
    category: 'Hệ điều hành',
    imageUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '5',
    title: 'Tối ưu hóa tốc độ Website WordPress với Redis và Varnish',
    excerpt: 'Hướng dẫn cấu hình Caching Layer giúp website của bạn tải nhanh gấp 10 lần trên hạ tầng VPS SSD.',
    date: '05/06/2024',
    author: 'DevOps',
    category: 'Tối ưu',
    imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '6',
    title: 'IPv6 Rotating Proxy là gì? Ứng dụng trong Crawl Data',
    excerpt: 'Giải pháp tiết kiệm chi phí cho việc thu thập dữ liệu quy mô lớn mà không lo bị chặn IP.',
    date: '01/06/2024',
    author: 'Data Team',
    category: 'Proxy',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-efdeb6bf80d1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
  }
];

export const NAV_LINKS: NavLinkItem[] = [
  { name: 'Trang chủ', path: '/' },
  { 
    name: 'Sản phẩm', 
    path: '/pages/products',
    children: [
      { name: 'Anti-DDoS', path: `/pages/products?tab=${encodeURIComponent(ProductType.ANTI_DDOS)}` },
      { name: 'Cloud Server', path: `/pages/products?tab=${encodeURIComponent(ProductType.CLOUD_SERVER)}` },
      { name: 'Proxy Server', path: `/pages/products?tab=${encodeURIComponent(ProductType.PROXY)}` },
      { name: 'Máy chủ vật lý', path: `/pages/products?tab=${encodeURIComponent(ProductType.DEDICATED)}` },
      { name: 'VPS Hosting', path: `/pages/products?tab=${encodeURIComponent(ProductType.VPS)}` }, 
    ]
  },
  { 
    name: 'Đối tác', 
    path: '/pages/partners',
    children: [
      { name: 'Cộng tác viên', path: '/pages/partners#affiliate' },
      { name: 'Tích hợp API', path: '/pages/partners#api' },
    ] 
  },
  { name: 'Bài viết', path: '/pages/blog' },
  { name: 'Liên hệ', path: '/pages/contact' },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    role: "CEO TechViet",
    quote: "Hệ thống Cloud Server tại BowlanCloud rất ổn định, tốc độ NVMe giúp website của chúng tôi tải nhanh hơn 300% so với nhà cung cấp cũ.",
    avatar: "/av-u/32.jpg"
  },
  {
    id: 2,
    name: "Trần Thị B",
    role: "Marketing Manager",
    quote: "Dịch vụ Proxy 4G rất chất lượng, IP sạch giúp team mình chạy quảng cáo Facebook mượt mà, không lo bị checkpoint.",
    avatar: "/av-u/44.jpg"
  },
  {
    id: 3,
    name: "Lê Hoàng Nam",
    role: "Game Studio Lead",
    quote: "Hệ thống Anti-DDoS Game hoạt động cực kỳ hiệu quả. Server game của chúng tôi online 24/7 bất chấp các đợt tấn công lớn.",
    avatar: "/av-u/86.jpg"
  }
];