import { BlogPost, NavLinkItem, ProductPlan, ProductType } from "./types";

export const PRODUCT_PLANS: ProductPlan[] = [
  // Cloud Server
  {
    id: "cloud-1",
    name: "CLOUD VN 1-1-20",
    price: "70.000đ/tháng",
    cpu: "1 vCore",
    ram: "1 GB",
    disk: "20 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
  },
  {
    id: "cloud-2",
    name: "CLOUD VN 1-2-25",
    price: "90.000đ/tháng",
    cpu: "1 vCore",
    ram: "2 GB",
    disk: "25 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
    popular: true,
  },
  {
    id: "cloud-3",
    name: "CLOUD VN 2-4-30",
    price: "150.000đ/tháng",
    cpu: "2 vCore",
    ram: "4 GB",
    disk: "30 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
  },
  {
    id: "cloud-4",
    name: "CLOUD VN 4-8-50",
    price: "330.000đ/tháng",
    cpu: "4 vCore",
    ram: "8 GB",
    disk: "50 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
  },
  {
    id: "cloud-5",
    name: "CLOUD VN 8-16-70",
    price: "650.000đ/tháng",
    cpu: "8 vCore",
    ram: "16 GB",
    disk: "70 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
  },
  {
    id: "cloud-6",
    name: "CLOUD VN 8-32-100",
    price: "1.200.000đ/tháng",
    cpu: "8 vCore",
    ram: "32 GB",
    disk: "100 GB SSD",
    bandwidth: "100/100 Mbps",
    type: ProductType.CLOUD_SERVER,
    features: ["1 IP riêng", "Backup hàng ngày", "Window/Linux", "Hỗ trợ 24/7",'Cấu hình tùy chỉnh (Giá cả thay đổi theo cấu hình)'],
  },
  // Proxy
  {
    id: "proxy-1",
    name: "IPv4 Private Proxy",
    price: "30.000đ/proxy",
    cpu: "N/A",
    ram: "N/A",
    disk: "N/A",
    bandwidth: "Unlimited",
    type: ProductType.PROXY,
    features: [
      "IP tĩnh riêng biệt",
      "HTTP/SOCKS5",
      "Uptime 99.9%",
      "Nuôi Ebay/Amazon",
    ],
  },
  {
    id: "proxy-2",
    name: "Proxy Server VN",
    price: "50.000đ/tháng",
    cpu: "N/A",
    ram: "N/A",
    disk: "N/A",
    bandwidth: "100/100 Mbps",
    type: ProductType.PROXY,
    features: [
      "IP Riêng: IPv4",
      "HTTP/SOCKS5",
      "Hỗ trợ nhiều cổng",
      "Không giới hạn băng thông",
    ],
    popular: true,
  },
  {
    id: "proxy-3",
    name: "IPv6 Rotating",
    price: "200.000đ/tháng",
    cpu: "N/A",
    ram: "N/A",
    disk: "N/A",
    bandwidth: "Unlimited",
    type: ProductType.PROXY,
    features: [
      "Hàng triệu IP",
      "Xoay IP mỗi request",
      "Phù hợp Crawl Data",
      "Giá rẻ tiết kiệm",
    ],
  },
  {
    id: "proxy-4",
    name: "Residential Proxy",
    price: "150.000đ/GB",
    cpu: "N/A",
    ram: "N/A",
    disk: "N/A",
    bandwidth: "Theo dung lượng",
    type: ProductType.PROXY,
    features: [
      "IP dân cư thật",
      "Không bị block",
      "Target quốc gia",
      "Thanh toán PAYG",
    ],
  },
  // Dedicated
  {
    id: "dedi-1",
    name: "20C/40T DE62-VN",
    price: "2.800.000đ/tháng",
    cpu: "2x Xeon 2680v2",
    ram: "256 GB DDR3 ECC",
    disk: "800GB SSD",
    bandwidth: "1 Gbps",
    type: ProductType.DEDICATED,
    features: [
      "FPT Việt Nam",
      "Kết nối ổn định",
      "Hỗ trợ 24/7 VIP",
      "Bảo hành phần cứng",
      "Cấu hình tuỳ chọn (Giá cả thay đổi theo cấu hình)",
    ],
  },
  {
    id: "dedi-2",
    name: "28C/56T DE63-VN",
    price: "3.850.000đ/tháng",
    cpu: "2x Xeon 2680v4",
    ram: "128 GB DDR4 ECC",
    disk: "800GB  SSD",
    bandwidth: "1 Gbps",
    type: ProductType.DEDICATED,
    features: [
      "FPT Việt Nam",
      "Kết nối ổn định",
      "Hỗ trợ 24/7 VIP",
      "Bảo hành phần cứng",
      "Cấu hình tuỳ chọn (Giá cả thay đổi theo cấu hình)",
    ],
  },
  {
    id: "dedi-3",
    name: "40C/80T DE64-VN",
    price: "4.200.000đ/tháng",
    cpu: "2x Xeon Gold 6133",
    ram: "128 GB DDR4 ECC",
    disk: "800GB SSD",
    bandwidth: "1 Gbps",
    type: ProductType.DEDICATED,
    features: [
      "FPT Việt Nam",
      "Kết nối ổn định",
      "Hỗ trợ 24/7 VIP",
      "Bảo hành phần cứng",
      "Cấu hình tuỳ chọn (Giá cả thay đổi theo cấu hình)",
    ],
  },
  // Anti DDoS
  {
    id: "ddos-1",
    name: "Anti-DDoS Basic",
    price: "$70/month",
    cpu: "AI Filter",
    ram: "Global Node",
    disk: "N/A",
    bandwidth: "Clean Traffic",
    type: ProductType.ANTI_DDOS,
    features: [
      "Hỗ trợ 1 miền / tháng",
      "Bảo vệ DDoS mặt định",
      "Không giới hạn lưu lượng",
      "Không giới hạn băng thông",
    ],
  },
  {
    id: "ddos-2",
    name: "Anti-DDoS Pro",
    price: "$110/month",
    cpu: "Custom Rules",
    ram: "Multi-CDN",
    disk: "N/A",
    bandwidth: "Unlimited Clean",
    type: ProductType.ANTI_DDOS,
    features: [
      "Hỗ trợ 1 miền / tháng",
      "Tất cả tính năng cơ bản",
      "Tường lửa thông minh",
      "Hỗ trợ 24/7",
    ],
    popular: true,
  },
  {
    id: "ddos-3",
    name: "Anti-DDoS Premium",
    price: "$150/month",
    cpu: "Custom Rules",
    ram: "Multi-CDN",
    disk: "N/A",
    bandwidth: "Unlimited Clean",
    type: ProductType.ANTI_DDOS,
    features: [
      "Hỗ trợ 1 miền / tháng",
      "Tất cả tính năng nâng cao",
      "Tường lửa cao cấp",
      "Bảng điều khiển trực quan",
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "Tại sao nên chuyển từ Shared Hosting sang Cloud Server?",
    excerpt:
      "Khám phá những lợi ích vượt trội về hiệu năng, bảo mật và độ ổn định khi nâng cấp hệ thống của bạn lên Cloud Server NVMe.",
    date: "20/05/2024",
    author: "Admin",
    category: "Kiến thức",
    imageUrl:
      "/bg-nav/photo-1518770660439-4636190af475.avif",
    content: [
      { type: 'heading2', title: 'Giới thiệu' },
      { type: 'paragraph', content: 'Shared Hosting đã từng là lựa chọn phổ biến cho các website nhỏ vì chi phí rẻ. Tuy nhiên, khi website của bạn phát triển, những hạn chế của Shared Hosting sẽ dần lộ ra. Cloud Server là giải pháp tối ưu để giải quyết những vấn đề này.' },
      { type: 'heading2', title: 'Ưu điểm của Cloud Server so với Shared Hosting' },
      { type: 'heading3', title: '1. Hiệu năng vượt trội' },
      { type: 'paragraph', content: 'Với Cloud Server, bạn có toàn bộ tài nguyên CPU, RAM, và Disk riêng. Shared Hosting chia sẻ tài nguyên giữa hàng trăm website, khiến tốc độ website bị giảm đáng kể, đặc biệt khi có website khác sử dụng quá nhiều tài nguyên.' },
      { type: 'heading3', title: '2. Bảo mật cao hơn' },
      { type: 'paragraph', content: 'Cloud Server cung cấp môi trường cô lập hoàn toàn. Bạn không phải lo lắng về các vấn đề bảo mật từ những website khác trên cùng server như Shared Hosting.' },
      { type: 'heading3', title: '3. Tính năng quản trị toàn quyền' },
      { type: 'paragraph', content: 'Bạn có toàn bộ quyền truy cập Root/Administrator, cho phép cài đặt bất kỳ phần mềm nào cần thiết cho ứng dụng của mình.' },
      { type: 'heading3', title: '4. Độ ổn định cao' },
      { type: 'paragraph', content: 'Cloud Server sử dụng hạ tầng NVMe SSD hiện đại với uptime lên đến 99.9%, đảm bảo website của bạn hoạt động ổn định 24/7.' },
      { type: 'heading2', title: 'Kết luận' },
      { type: 'paragraph', content: 'Nếu website của bạn có lưu lượng truy cập cao hoặc yêu cầu tính năng nâng cao, nâng cấp lên Cloud Server là quyết định đúng đắn.' },
    ],
  },
  {
    id: "2",
    title: "Hướng dẫn cài đặt Proxy Server riêng tư an toàn",
    excerpt:
      "Bảo mật danh tính và dữ liệu của bạn trên internet với hướng dẫn thiết lập Proxy IPv4 Private chi tiết trên Linux.",
    date: "18/05/2024",
    author: "Kỹ thuật",
    category: "Hướng dẫn",
    imageUrl:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    content: [
      { type: 'heading2', title: 'Proxy Server là gì?' },
      { type: 'paragraph', content: 'Proxy Server là một máy chủ hoạt động như một trung gian giữa máy tính của bạn và internet. Nó che giấu địa chỉ IP thực của bạn, giúp bảo vệ quyền riêng tư và tăng cường bảo mật.' },
      { type: 'heading2', title: 'Chuẩn bị' },
      { type: 'paragraph', content: 'Trước khi bắt đầu, bạn cần chuẩn bị:' },
      { type: 'list', items: ['Một VPS hoặc Cloud Server chạy Ubuntu/CentOS', 'Kết nối SSH để truy cập server', 'Quyền root hoặc sudo'] },
      { type: 'heading2', title: 'Bước 1: Cập nhật hệ thống' },
      { type: 'paragraph', content: 'Mở terminal và chạy lệnh:' },
      { type: 'code', language: 'bash', content: 'sudo apt-get update && sudo apt-get upgrade' },
      { type: 'heading2', title: 'Bước 2: Cài đặt Proxy Server (Squid)' },
      { type: 'paragraph', content: 'Cài đặt Squid - một Proxy Server mạnh mẽ và phổ biến:' },
      { type: 'code', language: 'bash', content: 'sudo apt-get install squid' },
      { type: 'heading2', title: 'Bước 3: Cấu hình Proxy' },
      { type: 'paragraph', content: 'Chỉnh sửa file cấu hình:' },
      { type: 'code', language: 'bash', content: 'sudo nano /etc/squid/squid.conf' },
      { type: 'heading2', title: 'Kết luận' },
      { type: 'paragraph', content: 'Với hướng dẫn trên, bạn đã có thể thiết lập một Proxy Server riêng tư an toàn. Hãy kiểm tra cấu hình và khởi động dịch vụ để bắt đầu sử dụng.' },
    ],
  },
  {
    id: "3",
    title: "Anti-DDoS hoạt động như thế nào trong Game Online?",
    excerpt:
      "Tìm hiểu cơ chế hoạt động của các cuộc tấn công từ chối dịch vụ vào Game Server và giải pháp phòng chống hiệu quả.",
    date: "15/05/2024",
    author: "Security Team",
    category: "Bảo mật",
    imageUrl:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    content: [
      { type: 'heading2', title: 'DDoS Attack là gì?' },
      { type: 'paragraph', content: 'DDoS (Distributed Denial of Service) là một cuộc tấn công có mục đích làm cho server không khả dụng bằng cách gửi lưu lượng truy cập rất lớn từ nhiều nguồn khác nhau.' },
      { type: 'heading2', title: 'Những loại DDoS phổ biến' },
      { type: 'heading3', title: '1. Volume-based Attacks' },
      { type: 'paragraph', content: 'Tấn công dựa trên lượng dữ liệu khổng lồ, làm tắc đường truyền. Ví dụ: UDP floods, DNS amplification.' },
      { type: 'heading3', title: '2. Protocol Attacks' },
      { type: 'paragraph', content: 'Khai thác lỗ hổng trong giao thức mạng. Ví dụ: SYN floods, Ping of Death.' },
      { type: 'heading3', title: '3. Application Layer Attacks' },
      { type: 'paragraph', content: 'Tấn công mục tiêu vào các ứng dụng cụ thể. Ví dụ: HTTP flood, Slowloris.' },
      { type: 'heading2', title: 'Anti-DDoS hoạt động như thế nào?' },
      { type: 'paragraph', content: 'Giải pháp Anti-DDoS của BowlanCloud sử dụng nhiều kỹ thuật:' },
      { type: 'list', items: ['Traffic Filtering: Lọc lưu lượng độc hại trước khi đến server', 'Rate Limiting: Giới hạn số lượng yêu cầu từ một IP', 'Geo-blocking: Chặn lưu lượng từ các vùng địa lý không mong muốn', 'Machine Learning: Phát hiện mô hình tấn công mới'] },
      { type: 'heading2', title: 'Kết luận' },
      { type: 'paragraph', content: 'Với Anti-DDoS, game server của bạn sẽ an toàn khỏi các cuộc tấn công, đảm bảo trải nghiệm chơi game liên tục cho người chơi.' },
    ],
  },
  {
    id: "4",
    title: "Top 5 Distro Linux tốt nhất cho Web Server 2024",
    excerpt:
      "Đánh giá chi tiết ưu nhược điểm của Ubuntu, CentOS, Debian, AlmaLinux và Rocky Linux cho môi trường Production.",
    date: "10/06/2024",
    author: "SysAdmin",
    category: "Hệ điều hành",
    imageUrl:
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    content: [
      { type: 'heading2', title: 'Tầm quan trọng của việc chọn Distro Linux đúng' },
      { type: 'paragraph', content: 'Lựa chọn Distro Linux phù hợp là bước quan trọng khi thiết lập web server. Mỗi distro có những ưu điểm và nhược điểm khác nhau.' },
      { type: 'heading2', title: '1. Ubuntu Server' },
      { type: 'paragraph', content: 'Ưu điểm: Dễ sử dụng, hỗ trợ tốt, cộng đồng lớn, cập nhật thường xuyên.' },
      { type: 'paragraph', content: 'Nhược điểm: Phát hành mới nhanh có thể không ổn định.' },
      { type: 'paragraph', content: 'Phù hợp cho: Người mới bắt đầu, startup.' },
      { type: 'heading2', title: '2. CentOS / RHEL' },
      { type: 'paragraph', content: 'Ưu điểm: Ổn định cực cao, hỗ trợ lâu dài, phổ biến trong enterprise.' },
      { type: 'paragraph', content: 'Nhược điểm: Cập nhật chậm, có phí cho RHEL.' },
      { type: 'paragraph', content: 'Phù hợp cho: Doanh nghiệp, ứng dụng quan trọng.' },
      { type: 'heading2', title: '3. Debian' },
      { type: 'paragraph', content: 'Ưu điểm: Rất ổn định, cộng đồng mạnh, quản lý gói xuất sắc.' },
      { type: 'paragraph', content: 'Nhược điểm: Cập nhật chậm hơn Ubuntu.' },
      { type: 'paragraph', content: 'Phù hợp cho: Server dài hạn cần độ ổn định tối đa.' },
      { type: 'heading2', title: '4. AlmaLinux' },
      { type: 'paragraph', content: 'Ưu điểm: Thay thế CentOS tốt, miễn phí, ổn định.' },
      { type: 'paragraph', content: 'Nhược điểm: Cộng đồng nhỏ hơn CentOS.' },
      { type: 'paragraph', content: 'Phù hợp cho: Doanh nghiệp muốn thay thế CentOS.' },
      { type: 'heading2', title: '5. Rocky Linux' },
      { type: 'paragraph', content: 'Ưu điểm: Tương thích CentOS, sự hỗ trợ từ cộng đồng.' },
      { type: 'paragraph', content: 'Nhược điểm: Còn mới, cộng đồng chưa lớn.' },
      { type: 'paragraph', content: 'Phù hợp cho: Doanh nghiệp tìm kiếm thay thế CentOS mới.' },
      { type: 'heading2', title: 'Kết luận' },
      { type: 'paragraph', content: 'Không có distro "tốt nhất" duy nhất - hãy chọn dựa trên nhu cầu cụ thể của bạn.' },
    ],
  },
  {
    id: "5",
    title: "Tối ưu hóa tốc độ Website WordPress với Redis và Varnish",
    excerpt:
      "Hướng dẫn cấu hình Caching Layer giúp website của bạn tải nhanh gấp 10 lần trên hạ tầng VPS SSD.",
    date: "05/06/2024",
    author: "DevOps",
    category: "Tối ưu",
    imageUrl:
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    content: [
      { type: 'heading2', title: 'Tầm quan trọng của Caching' },
      { type: 'paragraph', content: 'Caching là kỹ thuật lưu trữ dữ liệu thường xuyên sử dụng để truy cập nhanh hơn. Đối với WordPress, caching có thể giảm thời gian tải trang đáng kể.' },
      { type: 'heading2', title: 'Redis là gì?' },
      { type: 'paragraph', content: 'Redis là một kho dữ liệu in-memory (RAM) tốc độ cao, hoàn hảo cho việc lưu trữ cache. Nó có thể xử lý hàng triệu yêu cầu mỗi giây.' },
      { type: 'heading2', title: 'Varnish là gì?' },
      { type: 'paragraph', content: 'Varnish là một HTTP accelerator - cache lớp cao nhất giữa người dùng và server. Nó lưu trữ các trang HTML đã được render.' },
      { type: 'heading2', title: 'Cấu trúc tối ưu' },
      { type: 'code', language: 'text', content: 'User → Varnish (HTTP Cache) → WordPress → Redis (Object Cache)' },
      { type: 'heading2', title: 'Bước cài đặt cơ bản' },
      { type: 'heading3', title: 'Cài đặt Redis' },
      { type: 'code', language: 'bash', content: 'sudo apt-get install redis-server' },
      { type: 'heading3', title: 'Cài đặt Varnish' },
      { type: 'code', language: 'bash', content: 'sudo apt-get install varnish' },
      { type: 'heading3', title: 'Cài WordPress Plugin' },
      { type: 'paragraph', content: 'Sử dụng plugin "Redis Object Cache" hoặc "WP Redis" để kết nối WordPress với Redis.' },
      { type: 'heading2', title: 'Kết quả' },
      { type: 'paragraph', content: 'Sau khi cấu hình, bạn sẽ thấy tốc độ tải trang giảm từ 2-3 giây xuống 0.3-0.5 giây.' },
    ],
  },
  {
    id: "6",
    title: "IPv6 Rotating Proxy là gì? Ứng dụng trong Crawl Data",
    excerpt:
      "Giải pháp tiết kiệm chi phí cho việc thu thập dữ liệu quy mô lớn mà không lo bị chặn IP.",
    date: "01/06/2024",
    author: "Data Team",
    category: "Proxy",
    imageUrl:
      "/bg-nav/photo-1518770660439-4636190af475.avif",
    content: [
      { type: 'heading2', title: 'IPv6 Rotating Proxy là gì?' },
      { type: 'paragraph', content: 'IPv6 Rotating Proxy là một dịch vụ cung cấp hàng triệu địa chỉ IPv6 khác nhau. Mỗi yêu cầu HTTP được gửi từ một IP khác, tạo cảm giác như lưu lượng đến từ nhiều người dùng thực.' },
      { type: 'heading2', title: 'Tại sao cần Rotating Proxy?' },
      { type: 'paragraph', content: 'Nhiều website chặn các yêu cầu quá tần suất từ cùng một IP để ngăn chặn:' },
      { type: 'list', items: ['Web scraping/crawling', 'Bot abuse', 'DDoS attacks'] },
      { type: 'heading2', title: 'Ưu điểm của IPv6 Rotating' },
      { type: 'heading3', title: '1. Không bị chặn' },
      { type: 'paragraph', content: 'Với hàng triệu IP, website khó có thể chặn hết. Nếu một IP bị chặn, bạn có thể chuyển sang IP khác.' },
      { type: 'heading3', title: '2. Giá rẻ' },
      { type: 'paragraph', content: 'IPv6 có rất nhiều địa chỉ khả dụng, nên chi phí thấp hơn IPv4 private proxy.' },
      { type: 'heading3', title: '3. Tốc độ cao' },
      { type: 'paragraph', content: 'Không bị giới hạn băng thông, cho phép crawl dữ liệu nhanh chóng.' },
      { type: 'heading2', title: 'Ứng dụng thực tế' },
      { type: 'heading3', title: 'Web Scraping' },
      { type: 'paragraph', content: 'Thu thập dữ liệu từ các website lớn mà không bị chặn.' },
      { type: 'heading3', title: 'SEO Monitoring' },
      { type: 'paragraph', content: 'Kiểm tra xếp hạng từ khóa từ các vị trí địa lý khác nhau.' },
      { type: 'heading3', title: 'Price Monitoring' },
      { type: 'paragraph', content: 'Theo dõi giá cả sản phẩm trên các trang thương mại điện tử.' },
      { type: 'heading2', title: 'Kết luận' },
      { type: 'paragraph', content: 'IPv6 Rotating Proxy là giải pháp lý tưởng cho các dự án cần crawl dữ liệu quy mô lớn với chi phí thấp.' },
    ],
  },
];

export const NAV_LINKS: NavLinkItem[] = [
  { name: "Trang chủ", path: "/" },
  {
    name: "Sản phẩm",
    path: "/pages/products",
    children: [
      {
        name: "Anti-DDoS",
        path: `/pages/products?tab=${encodeURIComponent(
          ProductType.ANTI_DDOS
        )}`,
      },
      {
        name: "Cloud Server",
        path: `/pages/products?tab=${encodeURIComponent(
          ProductType.CLOUD_SERVER
        )}`,
      },
      {
        name: "Máy chủ vật lý",
        path: `/pages/products?tab=${encodeURIComponent(
          ProductType.DEDICATED
        )}`,
      },
      {
        name: "Proxy Server",
        path: `/pages/products?tab=${encodeURIComponent(ProductType.PROXY)}`,
      },
    ],
  },
  {
    name: "Đối tác",
    path: "/pages/partners",
    children: [
      { name: "Cộng tác viên", path: "/pages/partners#affiliate" },
      { name: "Tích hợp API", path: "/pages/partners#api" },
    ],
  },
  { name: "Bài viết", path: "/pages/blog" },
  { name: "Liên hệ", path: "/pages/contact" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    role: "CEO TechViet",
    quote:
      "Hệ thống Cloud Server tại BowlanCloud rất ổn định, tốc độ NVMe giúp website của chúng tôi tải nhanh hơn 300% so với nhà cung cấp cũ.",
    avatar: "/av-u/32.jpg",
  },
  {
    id: 2,
    name: "Trần Thị B",
    role: "Marketing Manager",
    quote:
      "Dịch vụ Proxy 4G rất chất lượng, IP sạch giúp team mình chạy quảng cáo Facebook mượt mà, không lo bị checkpoint.",
    avatar: "/av-u/44.jpg",
  },
  {
    id: 3,
    name: "Lê Hoàng Nam",
    role: "Game Studio Lead",
    quote:
      "Hệ thống Anti-DDoS Game hoạt động cực kỳ hiệu quả. Server game của chúng tôi online 24/7 bất chấp các đợt tấn công lớn.",
    avatar: "/av-u/86.jpg",
  },
];
